Repository APPS-sookmyung/2024-WELLET-Server, pull requests merged in 2024-08, with the labels that each got.

#30 [Feat] 엔티티 연결
  src/main/java/WELLET/welletServer/card/domain/Card.java
  src/main/java/WELLET/welletServer/category/domain/Category.java
  src/main/java/WELLET/welletServer/member/domain/Member.java
Labels: 🧡해림, 🚨MVP, ✨Feature

#33 [Fix] 명함 관련 디테일 수정
  src/main/java/WELLET/welletServer/card/controller/CardController.java
  src/main/java/WELLET/welletServer/card/domain/Card.java
  src/main/java/WELLET/welletServer/card/dto/CardCountResponseDto.java
  src/main/java/WELLET/welletServer/card/dto/CardListResponse.java
  src/main/java/WELLET/welletServer/card/dto/CardResponse.java
  src/main/java/WELLET/welletServer/card/dto/CardSaveDto.java
  src/main/java/WELLET/welletServer/card/service/CardService.java
  src/main/java/WELLET/welletServer/category/domain/Category.java
  src/main/java/WELLET/welletServer/category/dto/CardListResponse.java
  src/main/java/WELLET/welletServer/category/reponsitory/CategoryRepository.java
  src/main/java/WELLET/welletServer/category/service/CategoryService.java
  src/main/java/WELLET/welletServer/categoryCard/domain/CategoryCard.java
  src/main/java/WELLET/welletServer/categoryCard/repository/CategoryCardRepository.java
  src/main/java/WELLET/welletServer/categoryCard/service/CategoryCardService.java
  src/main/java/WELLET/welletServer/member/domain/Member.java
  src/main/java/WELLET/welletServer/member/service/MemberService.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#35 [Feat] CORS 설정
  .DS_Store
  src/main/java/WELLET/welletServer/config/SecurityConfig.java
Labels: ☁️⚡️아정, 🚨MVP, ✨Feature

#37 [Feat] 그룹 관련 디테일 수정
  src/main/java/WELLET/welletServer/category/controller/CategoryController.java
  src/main/java/WELLET/welletServer/category/domain/Category.java
  src/main/java/WELLET/welletServer/category/dto/CardListResponse.java
  src/main/java/WELLET/welletServer/category/dto/CategoryCardListResponse.java
  src/main/java/WELLET/welletServer/category/service/CategoryService.java
  src/main/java/WELLET/welletServer/categoryCard/domain/CategoryCard.java
  src/main/java/WELLET/welletServer/categoryCard/repository/CategoryCardRepository.java
  src/main/java/WELLET/welletServer/categoryCard/service/CategoryCardService.java
Labels: 🧡해림, 🚨MVP, 🔧Fix

#38 [Feat] 이름으로 검색기능
  src/main/java/WELLET/welletServer/card/Repository/CardRepository.java
  src/main/java/WELLET/welletServer/card/controller/CardController.java
  src/main/java/WELLET/welletServer/card/service/CardService.java
Labels: 🐢예영, 🚨MVP, ✨Feature

#47 [Feat] 명함 로직 swagger 애노테이션 추가
  .gitignore
  src/main/java/WELLET/welletServer/card/controller/CardController.java
  src/main/java/WELLET/welletServer/card/dto/CardCountResponseDto.java
  src/main/java/WELLET/welletServer/card/dto/CardListResponse.java
  src/main/java/WELLET/welletServer/card/dto/CardResponse.java
  src/main/java/WELLET/welletServer/card/dto/CardSaveDto.java
  src/main/java/WELLET/welletServer/card/dto/CardUpdateDto.java
  src/main/java/WELLET/welletServer/category/exception/CategoryErrorCode.java
  src/main/java/WELLET/welletServer/category/service/CategoryService.java
Labels: ☁️⚡️아정, 🚨MVP, ✨Feature

#46 [Feat] 그룹별 명함 조회 예외처리
  src/main/java/WELLET/welletServer/category/service/CategoryService.java
Labels: 🧡해림, 🚨MVP, ✨Feature

#44 [Feat] 검색기능 예외처리
  src/main/java/WELLET/welletServer/card/controller/CardController.java
  src/main/java/WELLET/welletServer/card/service/CardService.java
Labels: 🐢예영, 🚨MVP, ✨Feature

#48 [Feat] 카테고리 스웨거 애노테이션 적용
  src/main/java/WELLET/welletServer/category/controller/CategoryController.java
  src/main/java/WELLET/welletServer/category/dto/CategoryCardListResponse.java
  src/main/java/WELLET/welletServer/category/dto/CategoryListName.java
  src/main/java/WELLET/welletServer/category/dto/CategorySaveDto.java
  src/main/java/WELLET/welletServer/category/dto/CategoryUpdateDto.java
Labels: 🧡해림, 🚨MVP, ✨Feature

#49 [Feat] 회원저장 예외처리 및 멤버 스웨거 적용
  src/main/java/WELLET/welletServer/member/controller/MemberController.java
  src/main/java/WELLET/welletServer/member/dto/MemberSaveDto.java
  src/main/java/WELLET/welletServer/member/dto/MemberUpdateDto.java
  src/main/java/WELLET/welletServer/member/exception/MemberErrorCode.java
  src/main/java/WELLET/welletServer/member/repository/MemberRepository.java
  src/main/java/WELLET/welletServer/member/service/MemberService.java
Labels: 🐢예영, 🚨MVP, ✨Feature

#52 [Feat] Dockerfile 작성
  .github/workflows/github-actions.yml
  .gitignore
  Dockerfile
  build.gradle
  gradlew
Labels: ☁️⚡️아정, 🚨MVP, ✨Feature

#53 [Feat] 1차 배포 및 CI/CD 구축
  .DS_Store
  .github/ISSUE_TEMPLATE/-feat--.md
  .github/workflows/github-actions.yml
  .gitignore
  Dockerfile
  build.gradle
  gradlew
  settings.gradle
  src/main/java/WELLET/welletServer/HealthCheck.java
  src/main/java/WELLET/welletServer/WelletServerApplication.java
  src/main/java/WELLET/welletServer/card/Repository/CardRepository.java
  src/main/java/WELLET/welletServer/card/controller/CardController.java
  src/main/java/WELLET/welletServer/card/domain/Card.java
  src/main/java/WELLET/welletServer/card/dto/CardCountResponseDto.java
  src/main/java/WELLET/welletServer/card/dto/CardListResponse.java
  src/main/java/WELLET/welletServer/card/dto/CardResponse.java
  src/main/java/WELLET/welletServer/card/dto/CardSaveDto.java
  src/main/java/WELLET/welletServer/card/dto/CardUpdateDto.java
  src/main/java/WELLET/welletServer/card/exception/CardErrorCode.java
  src/main/java/WELLET/welletServer/card/exception/CardException.java
  src/main/java/WELLET/welletServer/card/service/CardService.java
  src/main/java/WELLET/welletServer/category/controller/CategoryController.java
  src/main/java/WELLET/welletServer/category/domain/Category.java
  src/main/java/WELLET/welletServer/category/dto/CategoryCardListResponse.java
  src/main/java/WELLET/welletServer/category/dto/CategoryListName.java
  src/main/java/WELLET/welletServer/category/dto/CategorySaveDto.java
  src/main/java/WELLET/welletServer/category/dto/CategoryUpdateDto.java
  src/main/java/WELLET/welletServer/category/exception/CategoryErrorCode.java
  src/main/java/WELLET/welletServer/category/exception/CategoryException.java
  src/main/java/WELLET/welletServer/category/reponsitory/CategoryRepository.java
  src/main/java/WELLET/welletServer/category/service/CategoryService.java
  src/main/java/WELLET/welletServer/categoryCard/domain/CategoryCard.java
  src/main/java/WELLET/welletServer/categoryCard/repository/CategoryCardRepository.java
  src/main/java/WELLET/welletServer/categoryCard/service/CategoryCardService.java
  src/main/java/WELLET/welletServer/common/BaseTimeEntity.java
  src/main/java/WELLET/welletServer/common/GlobalExceptionHandler.java
  src/main/java/WELLET/welletServer/common/response/BasicResponse.java
  src/main/java/WELLET/welletServer/common/response/ErrorEntity.java
  src/main/java/WELLET/welletServer/common/response/ResponseUtil.java
  src/main/java/WELLET/welletServer/config/SecurityConfig.java
  src/main/java/WELLET/welletServer/config/SwaggerConfig.java
  src/main/java/WELLET/welletServer/member/controller/MemberController.java
  src/main/java/WELLET/welletServer/member/domain/Member.java
  src/main/java/WELLET/welletServer/member/dto/MemberSaveDto.java
  src/main/java/WELLET/welletServer/member/dto/MemberUpdateDto.java
  src/main/java/WELLET/welletServer/member/exception/MemberErrorCode.java
  src/main/java/WELLET/welletServer/member/exception/MemberException.java
  src/main/java/WELLET/welletServer/member/repository/MemberRepository.java
  src/main/java/WELLET/welletServer/member/service/MemberService.java
  src/main/java/weletserver/welet/HealthCheck.java
  src/test/java/WELLET/welletServer/WelletServerApplicationTests.java
Labels: ☁️⚡️아정, 🚨MVP, ✨Feature

#56 [Feat] s3 연동
  build.gradle
  src/main/java/WELLET/welletServer/HealthCheck.java
  src/main/java/WELLET/welletServer/files/FileUploader.java
  src/main/java/WELLET/welletServer/files/S3Config.java
  src/main/java/WELLET/welletServer/files/S3FileUploader.java
  src/main/java/WELLET/welletServer/files/S3IOException.java
  src/main/java/WELLET/welletServer/files/TestFileUploader.java
Labels: ☁️⚡️아정, 🚨MVP, ✨Feature

#58 [Fix] 명함 생성 api 수정
  src/main/java/WELLET/welletServer/card/domain/Card.java
  src/main/java/WELLET/welletServer/card/dto/CardSaveDto.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#60 [Feat] 내 명함 로직 구현 및 멤버 로직 연결
  src/main/java/WELLET/welletServer/card/Repository/CardRepository.java
  src/main/java/WELLET/welletServer/card/controller/CardController.java
  src/main/java/WELLET/welletServer/card/controller/MyCardController.java
  src/main/java/WELLET/welletServer/card/domain/Card.java
  src/main/java/WELLET/welletServer/card/dto/CardResponse.java
  src/main/java/WELLET/welletServer/card/dto/MyCardSaveDto.java
  src/main/java/WELLET/welletServer/card/dto/MyCardUpdateDto.java
  src/main/java/WELLET/welletServer/card/exception/CardErrorCode.java
  src/main/java/WELLET/welletServer/card/exception/CardException.java
  src/main/java/WELLET/welletServer/card/service/CardService.java
  src/main/java/WELLET/welletServer/card/service/MyCardService.java
  src/main/java/WELLET/welletServer/categoryCard/service/CategoryCardService.java
  src/main/java/WELLET/welletServer/member/controller/MemberController.java
Labels: ☁️⚡️아정, 🚨MVP, ✨Feature

#64 [Fix] 깃허브 액션 스크립트 수정
  .github/workflows/github-actions.yml
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#65 [Fix] 깃허브 액션 스크립트 수정
  .github/workflows/github-actions.yml
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#70 [Fix] CORS 오류 수정
  src/main/java/WELLET/welletServer/config/SecurityConfig.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#71 [Fix] CORS 오류 수정
  src/main/java/WELLET/welletServer/config/SecurityConfig.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#72 [Fix] CORS 오류 수정
  src/main/java/WELLET/welletServer/config/SecurityConfig.java
Labels: ☁️⚡️아정, 🚨MVP, ✨Feature

#73 [Fix] CORS 오류 수정
  src/main/java/WELLET/welletServer/config/SecurityConfig.java
Labels: ☁️⚡️아정, 🚨MVP, ✨Feature

#74 [Fix] cors 오류 최종 수정
  src/main/java/WELLET/welletServer/config/SecurityConfig.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#75 [Fix] cors 오류 최종 수정
  src/main/java/WELLET/welletServer/config/SecurityConfig.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix
