Repository APPS-sookmyung/2024-WELLET-Server, pull requests merged in 2024-12, with the labels that each got.

#122 [Fix] 이미지 수정 예외 처리
  src/main/java/WELLET/welletServer/card/controller/CardController.java
  src/main/java/WELLET/welletServer/card/dto/CardResponse.java
  src/main/java/WELLET/welletServer/card/dto/MyCardSaveDto.java
  src/main/java/WELLET/welletServer/card/service/CardService.java
  src/main/java/WELLET/welletServer/card/service/MyCardService.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#129 [Fix] jwt 바디 담기
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: 🧡해림, 🚨MVP, 🔧Fix

#134 [Feat] text 서버 올리기
  .github/workflows/github-actions.yml
  src/main/java/WELLET/welletServer/config/CookieAttributeFilter.java
  src/main/java/WELLET/welletServer/config/CorsMvcConfig.java
  src/main/java/WELLET/welletServer/config/SecurityConfig.java
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
  src/main/resources/static/.well-known/pki-validation/68C418F7BF64BE9C507689BD920D424B.txt
Labels: 🧡해림, 🚨MVP, ✨Feature

#137 [Feat] 인증서 발급을 위한 p 옵션 추가
  .github/workflows/github-actions.yml
Labels: 🧡해림, 🚨MVP, ✨Feature

#139 [Fix] action.yml 수정
  .github/workflows/github-actions.yml
Labels: 🧡해림, 🚨MVP, 🔧Fix

#141 [Fix] | 추가
  .github/workflows/github-actions.yml
Labels: 🧡해림, 🚨MVP, 🔧Fix

#143 [Fix] http 허용
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: 🧡해림, 🚨MVP, 🔧Fix

#145 [Fix] 강제 리다이렉트 방지
  src/main/java/WELLET/welletServer/config/SecurityConfig.java
Labels: 🧡해림, 🚨MVP, 🔧Fix

#160 [Fix] github-actions.yml docker-compose 추가
  .github/workflows/github-actions.yml
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#161 [Fix] github-actions.yml docker-compose 추가
  .github/workflows/github-actions.yml
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#162 Fix: ssh key 설정 추가 #149
  .github/workflows/github-actions.yml
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#163 [Fix] ssh 설정 추가
  .github/workflows/github-actions.yml
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#164 [Fix] cors 추가
  src/main/java/WELLET/welletServer/config/CorsMvcConfig.java
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#165 [Fix] cors 추가
  src/main/java/WELLET/welletServer/config/CorsMvcConfig.java
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#166 [Fix] cookie 수정
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#167 [Fix] 쿠키 수정
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#174 [Fix] 리다이렉트 url 교체
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#175 [Fix] 리다이렉트 url 교체
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#176 [Fix] 프론트엔드 url 세팅
  src/main/java/WELLET/welletServer/config/CorsMvcConfig.java
  src/main/java/WELLET/welletServer/config/SecurityConfig.java
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#177 [Fix] 프론트엔드 url 세팅
  src/main/java/WELLET/welletServer/config/CorsMvcConfig.java
  src/main/java/WELLET/welletServer/config/SecurityConfig.java
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#178 [Fix] 리다이렉트 url 수정
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#179 [Fix] 리다이렉트 url 수정
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#180 [Feat] 로그인 url 추가
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#181 [Feat] 로그인 url 추가
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#182 [Fix] cors 수정
  src/main/java/WELLET/welletServer/config/CorsMvcConfig.java
  src/main/java/WELLET/welletServer/config/SecurityConfig.java
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#183 [Fix] cors 수정
  src/main/java/WELLET/welletServer/config/CorsMvcConfig.java
  src/main/java/WELLET/welletServer/config/SecurityConfig.java
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#184 [Del] remove redirect URL
  src/main/java/WELLET/welletServer/config/CorsMvcConfig.java
  src/main/java/WELLET/welletServer/config/SecurityConfig.java
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#185 [Del] remove redirect URL
  src/main/java/WELLET/welletServer/config/CorsMvcConfig.java
  src/main/java/WELLET/welletServer/config/SecurityConfig.java
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#186 [Feat] 로그 추가
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#187 [Feat] 로그 추가
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#188 [Fix] setSecure(ture) 옵션 제거
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#189 [Fix] setSecure(ture) 옵션 제거
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#190 [Fix] https 속성 추가
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#191 [Fix] https 속성 추가
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#192 [Feat] CORS 오류
  src/main/java/WELLET/welletServer/config/CorsMvcConfig.java
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#193 [Feat] CORS 오류 수정
  src/main/java/WELLET/welletServer/config/CorsMvcConfig.java
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#194 [Fix] 도메인 수정
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#195 [Fix] 도메인 수정
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#196 [Fix] header cookie 값 조정
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#197 [Fix] header cookie 값 조정
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#198 [Fix] 쿠키 추가
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#199 [Fix] 쿠키 추가
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#200 [Feat] 도메인 추가
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#201 [Feat] 도메인 추가
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#202 [Fix] Redirect URL 수정
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#203 [Fix] Redirect URL 수정
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#206 [Fix] cookie 설정
  src/main/java/WELLET/welletServer/config/CorsMvcConfig.java
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#207 [Fix] cookie 설정
  src/main/java/WELLET/welletServer/config/CorsMvcConfig.java
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix
