Repository APPS-sookmyung/2024-WELLET-Server, pull requests merged in 2024-11, with the labels that each got.

#68 [Feat] 이미지파일 업로드 및 수정 기능
  .DS_Store
  src/main/java/WELLET/welletServer/card/Repository/CardImageRepository.java
  src/main/java/WELLET/welletServer/card/Repository/CardRepository.java
  src/main/java/WELLET/welletServer/card/controller/CardController.java
  src/main/java/WELLET/welletServer/card/controller/MyCardController.java
  src/main/java/WELLET/welletServer/card/domain/Card.java
  src/main/java/WELLET/welletServer/card/domain/CardImage.java
  src/main/java/WELLET/welletServer/card/dto/CardResponse.java
  src/main/java/WELLET/welletServer/card/dto/CardSaveDto.java
  src/main/java/WELLET/welletServer/card/dto/CardUpdateDto.java
  src/main/java/WELLET/welletServer/card/dto/MyCardResponse.java
  src/main/java/WELLET/welletServer/card/dto/MyCardSaveDto.java
  src/main/java/WELLET/welletServer/card/dto/MyCardUpdateDto.java
  src/main/java/WELLET/welletServer/card/service/CardService.java
  src/main/java/WELLET/welletServer/card/service/MyCardService.java
  src/main/java/WELLET/welletServer/category/controller/CategoryController.java
  src/main/java/WELLET/welletServer/member/controller/MemberController.java
  src/main/java/WELLET/welletServer/member/domain/Member.java
  src/main/java/WELLET/welletServer/member/dto/MemberSaveDto.java
  src/main/java/WELLET/welletServer/member/service/MemberService.java
Labels: 🐢예영, 🚨MVP, ✨Feature

#85 [Fix] 직책/부서 분리
  src/main/java/WELLET/welletServer/card/Repository/CardRepository.java
  src/main/java/WELLET/welletServer/card/domain/Card.java
  src/main/java/WELLET/welletServer/card/dto/CardListResponse.java
  src/main/java/WELLET/welletServer/card/dto/CardResponse.java
  src/main/java/WELLET/welletServer/card/dto/CardSaveDto.java
  src/main/java/WELLET/welletServer/card/dto/CardUpdateDto.java
  src/main/java/WELLET/welletServer/card/dto/MyCardResponse.java
  src/main/java/WELLET/welletServer/card/dto/MyCardSaveDto.java
  src/main/java/WELLET/welletServer/card/dto/MyCardUpdateDto.java
  src/main/java/WELLET/welletServer/card/service/CardService.java
  src/main/java/WELLET/welletServer/card/service/MyCardService.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#90 [Feat] 회원 목록 조회
  .gitignore
  src/main/java/WELLET/welletServer/member/controller/MemberController.java
  src/main/java/WELLET/welletServer/member/dto/MemberDto.java
  src/main/java/WELLET/welletServer/member/dto/MemberListDto.java
  src/main/java/WELLET/welletServer/member/service/MemberService.java
Labels: ☁️⚡️아정, 🚨MVP, ✨Feature

#92 [Fix] api 수정
  .gitignore
  src/main/java/WELLET/welletServer/card/controller/CardController.java
  src/main/java/WELLET/welletServer/card/controller/MyCardController.java
  src/main/java/WELLET/welletServer/category/controller/CategoryController.java
  src/main/java/WELLET/welletServer/member/controller/MemberController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#87 [Feat] 소셜 로그인 기능 구현
  .gitignore
  build.gradle
  src/main/java/WELLET/welletServer/kakaologin/Repository/UserRepository.java
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginPageController.java
  src/main/java/WELLET/welletServer/kakaologin/domain/KakaoUser.java
  src/main/java/WELLET/welletServer/kakaologin/dto/KakaoAccountDto.java
  src/main/java/WELLET/welletServer/kakaologin/dto/KakaoLoginDto.java
  src/main/java/WELLET/welletServer/kakaologin/dto/KakaoTokenResponseDto.java
  src/main/java/WELLET/welletServer/kakaologin/dto/KakaoUserInfoResponseDto.java
  src/main/java/WELLET/welletServer/kakaologin/dto/PartnerDto.java
  src/main/java/WELLET/welletServer/kakaologin/dto/ProfileDto.java
  src/main/java/WELLET/welletServer/kakaologin/jwt/JwtAuthenticationFilter.java
  src/main/java/WELLET/welletServer/kakaologin/jwt/JwtService.java
  src/main/java/WELLET/welletServer/kakaologin/security/SecurityConfig.java
  src/main/java/WELLET/welletServer/kakaologin/service/KakaoService.java
  src/main/java/WELLET/welletServer/kakaologin/service/UserService.java
Labels: 🧡해림, 🚨MVP, ✨Feature

#94 [Fix] 충돌 해결
  build.gradle
  src/main/java/WELLET/welletServer/card/controller/CardController.java
  src/main/java/WELLET/welletServer/card/controller/MyCardController.java
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginPageController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#98 [Fix] 내 명함 생성 코드 수정
  src/main/java/WELLET/welletServer/card/controller/MyCardController.java
  src/main/java/WELLET/welletServer/card/dto/MyCardUpdateDto.java
  src/main/java/WELLET/welletServer/card/service/MyCardService.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#102 [Fix] .env -> application.yml
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginPageController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#103 [Fix] .env -> application.yml
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginPageController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#108 [Fix] 최종 수정
  src/main/java/WELLET/welletServer/card/controller/CardController.java
  src/main/java/WELLET/welletServer/card/controller/MyCardController.java
  src/main/java/WELLET/welletServer/card/service/MyCardService.java
  src/main/java/WELLET/welletServer/category/controller/CategoryController.java
  src/main/java/WELLET/welletServer/category/domain/Category.java
  src/main/java/WELLET/welletServer/common/GlobalExceptionHandler.java
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginPageController.java
  src/main/java/WELLET/welletServer/kakaologin/exception/TokenErrorCode.java
  src/main/java/WELLET/welletServer/kakaologin/exception/TokenException.java
  src/main/java/WELLET/welletServer/kakaologin/jwt/JwtService.java
  src/main/java/WELLET/welletServer/kakaologin/service/UserService.java
  src/main/java/WELLET/welletServer/member/controller/MemberController.java
  src/main/java/WELLET/welletServer/member/service/MemberService.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#109 [Fix] 최종 수정
  src/main/java/WELLET/welletServer/card/controller/CardController.java
  src/main/java/WELLET/welletServer/card/controller/MyCardController.java
  src/main/java/WELLET/welletServer/card/service/CardService.java
  src/main/java/WELLET/welletServer/card/service/MyCardService.java
  src/main/java/WELLET/welletServer/category/controller/CategoryController.java
  src/main/java/WELLET/welletServer/category/domain/Category.java
  src/main/java/WELLET/welletServer/common/GlobalExceptionHandler.java
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginController.java
  src/main/java/WELLET/welletServer/kakaologin/controller/KakaoLoginPageController.java
  src/main/java/WELLET/welletServer/kakaologin/exception/TokenErrorCode.java
  src/main/java/WELLET/welletServer/kakaologin/exception/TokenException.java
  src/main/java/WELLET/welletServer/kakaologin/jwt/JwtService.java
  src/main/java/WELLET/welletServer/kakaologin/service/UserService.java
  src/main/java/WELLET/welletServer/member/controller/MemberController.java
  src/main/java/WELLET/welletServer/member/exception/MemberErrorCode.java
  src/main/java/WELLET/welletServer/member/service/MemberService.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#111 [Fix] myCard Member 추가
  src/main/java/WELLET/welletServer/card/service/MyCardService.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#112 [Fix] 카테고리 인가 연동
  src/main/java/WELLET/welletServer/category/controller/CategoryController.java
  src/main/java/WELLET/welletServer/category/service/CategoryService.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#114 [Fix] 카테고리 인가 연동
  src/main/java/WELLET/welletServer/category/controller/CategoryController.java
  src/main/java/WELLET/welletServer/category/service/CategoryService.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#115 [Fix] null 예외 처리
  src/main/java/WELLET/welletServer/card/controller/CardController.java
  src/main/java/WELLET/welletServer/card/domain/Card.java
  src/main/java/WELLET/welletServer/card/domain/CardImage.java
  src/main/java/WELLET/welletServer/card/service/CardService.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#119 [Fix] CORS 수정
  src/main/java/WELLET/welletServer/config/SecurityConfig.java
Labels: 🧡해림, 🚨MVP, 🔧Fix
