Repository APPS-sookmyung/2024-WELLET-Server, pull requests merged in 2024-09, with the labels that each got.

#78 [Fix] 기본 응답 객체 삭제
  src/main/java/WELLET/welletServer/HealthCheck.java
  src/main/java/WELLET/welletServer/card/controller/CardController.java
  src/main/java/WELLET/welletServer/card/controller/MyCardController.java
  src/main/java/WELLET/welletServer/category/controller/CategoryController.java
  src/main/java/WELLET/welletServer/common/GlobalExceptionHandler.java
  src/main/java/WELLET/welletServer/common/response/BasicResponse.java
  src/main/java/WELLET/welletServer/common/response/ErrorEntity.java
  src/main/java/WELLET/welletServer/common/response/ResponseUtil.java
  src/main/java/WELLET/welletServer/member/controller/MemberController.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#81 [Feat] 기본 응답 객체 삭제 및 명함별 카테고리 조회 api 수정
  src/main/java/WELLET/welletServer/HealthCheck.java
  src/main/java/WELLET/welletServer/card/controller/CardController.java
  src/main/java/WELLET/welletServer/card/controller/MyCardController.java
  src/main/java/WELLET/welletServer/category/controller/CategoryController.java
  src/main/java/WELLET/welletServer/category/dto/CategoryListName.java
  src/main/java/WELLET/welletServer/category/service/CategoryService.java
  src/main/java/WELLET/welletServer/common/GlobalExceptionHandler.java
  src/main/java/WELLET/welletServer/common/response/BasicResponse.java
  src/main/java/WELLET/welletServer/common/response/ErrorEntity.java
  src/main/java/WELLET/welletServer/common/response/ResponseUtil.java
  src/main/java/WELLET/welletServer/member/controller/MemberController.java
Labels: ☁️⚡️아정, 🚨MVP, ✨Feature

#67 [Feat] 회사, 이름 등으로 검색
  src/main/java/WELLET/welletServer/card/Repository/CardRepository.java
  src/main/java/WELLET/welletServer/card/controller/CardController.java
  src/main/java/WELLET/welletServer/card/service/CardService.java
Labels: 🐢예영, 🚨MVP, ✨Feature

#82 [Fix] 중간 테이블 삭제 및 명함 이름 리턴 값 수정
  .DS_Store
  .github/workflows/github-actions.yml
  src/main/java/WELLET/welletServer/card/Repository/CardRepository.java
  src/main/java/WELLET/welletServer/card/controller/CardController.java
  src/main/java/WELLET/welletServer/card/domain/Card.java
  src/main/java/WELLET/welletServer/card/dto/CardResponse.java
  src/main/java/WELLET/welletServer/card/dto/CardSaveDto.java
  src/main/java/WELLET/welletServer/card/dto/CardUpdateDto.java
  src/main/java/WELLET/welletServer/card/dto/MyCardResponse.java
  src/main/java/WELLET/welletServer/card/exception/CardErrorCode.java
  src/main/java/WELLET/welletServer/card/service/CardService.java
  src/main/java/WELLET/welletServer/card/service/MyCardService.java
  src/main/java/WELLET/welletServer/category/controller/CategoryController.java
  src/main/java/WELLET/welletServer/category/domain/Category.java
  src/main/java/WELLET/welletServer/category/dto/CategoryCardListResponse.java
  src/main/java/WELLET/welletServer/category/dto/CategoryCountResponse.java
  src/main/java/WELLET/welletServer/category/reponsitory/CategoryRepository.java
  src/main/java/WELLET/welletServer/category/service/CategoryService.java
  src/main/java/WELLET/welletServer/categoryCard/domain/CategoryCard.java
  src/main/java/WELLET/welletServer/categoryCard/repository/CategoryCardRepository.java
  src/main/java/WELLET/welletServer/categoryCard/service/CategoryCardService.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix
