Repository APPS-sookmyung/2024-WELLET-Server, pull requests merged in 2024-07, with the labels that each got.

#22 [Fix] CardErrorCode 수정
  src/main/java/WELLET/welletServer/card/exception/CardErrorCode.java
  src/main/java/WELLET/welletServer/card/service/CardService.java
Labels: ☁️⚡️아정, 🚨MVP, 🔧Fix

#24 [Feat] 멤버 로직 구현
  src/main/java/WELLET/welletServer/common/BaseTimeEntity.java
  src/main/java/WELLET/welletServer/common/GlobalExceptionHandler.java
  src/main/java/WELLET/welletServer/member/controller/MemberController.java
  src/main/java/WELLET/welletServer/member/domain/Member.java
  src/main/java/WELLET/welletServer/member/dto/MemberSaveDto.java
  src/main/java/WELLET/welletServer/member/dto/MemberUpdateDto.java
  src/main/java/WELLET/welletServer/member/exception/MemberErrorCode.java
  src/main/java/WELLET/welletServer/member/exception/MemberException.java
  src/main/java/WELLET/welletServer/member/repository/MemberRepository.java
  src/main/java/WELLET/welletServer/member/service/MemberService.java
Labels: 🧡해림, 🚨MVP, ✨Feature

#27 [Feat] 그룹 로직 구현
  src/main/java/WELLET/welletServer/card/dto/CardListResponse.java
  src/main/java/WELLET/welletServer/category/controller/CategoryController.java
  src/main/java/WELLET/welletServer/category/domain/Category.java
  src/main/java/WELLET/welletServer/category/domain/CategoryCard.java
  src/main/java/WELLET/welletServer/category/dto/CardListResponse.java
  src/main/java/WELLET/welletServer/category/dto/CategoryListName.java
  src/main/java/WELLET/welletServer/category/dto/CategorySaveDto.java
  src/main/java/WELLET/welletServer/category/dto/CategoryUpdateDto.java
  src/main/java/WELLET/welletServer/category/exception/CategoryErrorCode.java
  src/main/java/WELLET/welletServer/category/exception/CategoryException.java
  src/main/java/WELLET/welletServer/category/reponsitory/CategoryRepository.java
  src/main/java/WELLET/welletServer/category/service/CategoryService.java
  src/main/java/WELLET/welletServer/common/GlobalExceptionHandler.java
Labels: 🧡해림, 🚨MVP, ✨Feature

#28 [Fix] 멤버 수정 로직
  src/main/java/WELLET/welletServer/member/domain/Member.java
  src/main/java/WELLET/welletServer/member/dto/MemberUpdateDto.java
  src/main/java/WELLET/welletServer/member/service/MemberService.java
Labels: 🧡해림, 🚨MVP, 🔧Fix
